
package presentacion.interfaz;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

public class InterfazReservar extends javax.swing.JDialog {
	private LocalDate fechaSeleccionada;
	private String hotelSeleccionado;

	/**
	 * Creates new form InterfazCalendar
	 */
	public InterfazReservar(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setVisible(true);
	}

	public LocalDate getFechaSeleccionada() {
		return fechaSeleccionada;
	}

	public void setFechaSeleccionada(LocalDate fechaSeleccionada) {
		this.fechaSeleccionada = fechaSeleccionada;
	}

	public String getHotelSeleccionado() {
		return hotelSeleccionado;
	}

	public void setHotelSeleccionado(String hotelSeleccionado) {
		this.hotelSeleccionado = hotelSeleccionado;
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		Date fecha = Fecha.getDate();

		if (fecha != null && ListaHoteles.getSelectedIndex() != -1) {
			fechaSeleccionada = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
			hotelSeleccionado = ListaHoteles.getSelectedValue();
			
		} else {
			Error.setText("Debe seleccionar todos los campos");
		}
		this.dispose();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ListaHoteles = new javax.swing.JList<>();
		jLabel1 = new javax.swing.JLabel();
		Fecha = new com.toedter.calendar.JDateChooser();
		jLabel2 = new javax.swing.JLabel();
		btnAceptar = new javax.swing.JButton();
		Error = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		ListaHoteles.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Hotel Ritz Madrid", "Hotel Arts Barcelona", "Gran Meliá Sevilla",
					"Hotel Alfonso XIII", "Hotel Bahía Santander", "Parador de Granada", "NH Collection Valencia Colón",
					"Barceló Málaga", "Hotel María Cristina San Sebastián", "Eurostars Palacio Buenavista Toledo",
					" " };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(ListaHoteles);

		jLabel1.setText("Selecciona el hotel");

		jLabel2.setText("Selecciona la fecha");

		btnAceptar.setText("Aceptar");
		btnAceptar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(110, 110, 110).addComponent(jLabel1))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(71, 71, 71).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(30, 30, 30).addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(130, 130, 130).addComponent(btnAceptar))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(67, 67, 67).addComponent(Error,
								javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(83, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGap(28, 28, 28).addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
						.addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnAceptar)
						.addGap(14, 14, 14)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel2,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel2,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JLabel Error;
	private com.toedter.calendar.JDateChooser Fecha;
	private javax.swing.JList<String> ListaHoteles;
	private javax.swing.JButton btnAceptar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration
}
