package presentacion.interfaz;

import java.util.List;

import javax.swing.JFrame;

import entidades.Cliente;
import presentacion.Presentador;

/**
 * @author andres
 */
public class MenuInterfaz extends JFrame {
	String valoresCliente[];
	Presentador pr;

	public MenuInterfaz(Presentador presentador) {
		initComponents();
		setVisible(true);
		valoresCliente = new String[3];
		pr = presentador;
	}

	public String[] getValoresCliente() {
		return valoresCliente;
	}

	public void setValoresCliente(String[] valoresCliente) {
		this.valoresCliente = valoresCliente;
	}

	private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {
		int opcionSeleccionada = ListaOpciones.getSelectedIndex(); // obtiene la opción seleccionada
		switch (opcionSeleccionada) {
		case 0:
			AltaCliente at = new AltaCliente(this, true);
			at.setVisible(true);
			conseguirValores(at);
			pr.introducirCliente(valoresCliente);
			break;
		case 1:
			pr.solicitarMostrarTodos();
			break;
		case 2:
			IntroducirId idInterfaz = new IntroducirId(this, true);
			int id = idInterfaz.getNumero();
			pr.solicitarMostrarPersona(id);
			break;
		case 3:
			IntroducirId idInterfazActualizar = new IntroducirId(this, true);
			int idActualizar = idInterfazActualizar.getNumero();
			pr.actualizarPersona(idActualizar);
			break;
		case 4:
			IntroducirId idInterfazBorrar = new IntroducirId(this, true);
			int idBorrar = idInterfazBorrar.getNumero();
			pr.eleminarPersona(idBorrar);
			break;
		default:
			throw new AssertionError();
		}
	}

	private void conseguirValores(AltaCliente at) {
		valoresCliente[0] = at.getNombre();
		valoresCliente[1] = at.getEmail();
		valoresCliente[2] = at.getTelefono();
	}

	public void mostrarClientes(List<Cliente> l) {
		TablaClientes tb = new TablaClientes(this, true, l);

	}

	public void actualizarPersona(Cliente c) {
		CambiarCliente cc = new CambiarCliente(this, true,c);

	}

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ListaOpciones = new javax.swing.JList<>();
		btnAceptar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Seleccione una opción:");

		ListaOpciones.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Introducir cliente", "Ver todos los clientes", "Buscar cliente por id",
					"Actualizar Cliente", "Eliminar Cliente" };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(ListaOpciones);

		btnAceptar.setText("Aceptar");
		btnAceptar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAceptarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(121, 121, 121).addComponent(jLabel1))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(144, 144, 144).addComponent(btnAceptar))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(103, 103, 103).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(109, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel1)
						.addGap(77, 77, 77)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(65, 65, 65).addComponent(btnAceptar).addContainerGap(90, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JList<String> ListaOpciones;
	private javax.swing.JButton btnAceptar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration

}
