package presentacion.interfaz;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import entidades.Cliente;
import entidades.Reserva;

/**
 *
 * @author andre
 */
public class Tabla extends javax.swing.JDialog {

    /**
     * Creates new form MostrarTodosCliente
     */
   
    
    
    
    
    

    public Tabla(MenuInterfaz menuInterfaz, boolean b) {
    	  super(menuInterfaz, b);
          initComponents();
          
         
	}






	public void mostrarClientes(List<Cliente> l) {
		DefaultTableModel modelo = Formatos.formatoCliente();
		modelo.setRowCount(0);
		
		for (Cliente cliente : l) {
		    modelo.addRow(new Object[]{
		            cliente.getId(),
		            cliente.getNombre(),
		            cliente.getEmail(),
		            cliente.getTelefono()
		        });
		}
		jTableClientes.setModel(modelo);
		setVisible(true);
	}

	public void mostrarReservas(List<Reserva>l) {
		DefaultTableModel modelo = Formatos.formatoReserva();
		modelo.setRowCount(0);
		for (Reserva r : l) {
		    modelo.addRow(new Object[]{
		            r.getCliente(),
		            r.getNombreCliente(),
		            r.getFecha().toString(),
		            r.getHabitacion(),
		            r.getHotel(),
		            
		        });
		}
		jTableClientes.setModel(modelo);
		setVisible(true);
	}




	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
   

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration                   
}
